/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import utility.DatabaseConnector;

/**
 *
 * @author jincheng
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    ArrayList<Patient> patients;
    Patient selectedPatient;
    ImageIcon profilePicture;
    Patient p1;

    /**
     * Creates new form FormJPanel
     */
    public ViewJPanel() {
        initComponents();
        populateTable();
    }
    
    public ViewJPanel(Patient p1){
        this.p1 = p1;
        this.patients = new ArrayList();
        initComponents();
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TitleJLabel = new javax.swing.JLabel();
        FirstNameJLabel = new javax.swing.JLabel();
        FirstNameJTextField = new javax.swing.JTextField();
        LastNameJTextField = new javax.swing.JTextField();
        LastNameJLabel = new javax.swing.JLabel();
        AgeJLabel = new javax.swing.JLabel();
        AgeJTextField = new javax.swing.JTextField();
        PhoneJLabel = new javax.swing.JLabel();
        PhoneJTextField = new javax.swing.JTextField();
        EmailJLabel = new javax.swing.JLabel();
        EmailJTextField = new javax.swing.JTextField();
        GenderJLabel = new javax.swing.JLabel();
        JRadioButtonMale = new javax.swing.JRadioButton();
        JRadioButtonFemale = new javax.swing.JRadioButton();
        JRadioButtonOthers = new javax.swing.JRadioButton();
        patientJComboBox = new javax.swing.JComboBox<>();
        patientTypeJLabel = new javax.swing.JLabel();
        submitEditedRowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientjTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        TitleJLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        TitleJLabel.setText("Registration");

        FirstNameJLabel.setText("First Name:");

        FirstNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameJTextFieldActionPerformed(evt);
            }
        });

        LastNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameJTextFieldActionPerformed(evt);
            }
        });

        LastNameJLabel.setText("Last Name:");

        AgeJLabel.setText("Age:");

        PhoneJLabel.setText("Phone Number:");

        EmailJLabel.setText("Email:");

        GenderJLabel.setText("Gender:");

        buttonGroupGender.add(JRadioButtonMale);
        JRadioButtonMale.setText("Male");
        JRadioButtonMale.setActionCommand("MALE");
        JRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(JRadioButtonFemale);
        JRadioButtonFemale.setText("Female");
        JRadioButtonFemale.setActionCommand("FEMALE");

        buttonGroupGender.add(JRadioButtonOthers);
        JRadioButtonOthers.setText("Prefer Not to Say");
        JRadioButtonOthers.setActionCommand("Others");

        patientJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointment", "Walk-in" }));
        patientJComboBox.setSelectedIndex(-1);

        patientTypeJLabel.setText("Patient Type:");

        submitEditedRowButton.setText("Submit");
        submitEditedRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditedRowButtonActionPerformed(evt);
            }
        });

        patientjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "firstName", "lastName", "age", "phoneNumber", "email", "gender", "patientType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientjTable);

        deleteButton.setText("Delete Row");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit Row");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(submitEditedRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(PhoneJLabel)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(AgeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LastNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(FirstNameJLabel))
                                            .addComponent(GenderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(patientTypeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JRadioButtonFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JRadioButtonOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(FirstNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LastNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AgeJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PhoneJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EmailJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientJComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton)
                                .addGap(55, 55, 55)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeJLabel)
                    .addComponent(AgeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailJLabel)
                    .addComponent(EmailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioButtonMale)
                    .addComponent(GenderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRadioButtonFemale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRadioButtonOthers)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientTypeJLabel))
                .addGap(27, 27, 27)
                .addComponent(submitEditedRowButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameJTextFieldActionPerformed

    private void LastNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameJTextFieldActionPerformed

    private void JRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButtonMaleActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = this.patientjTable.getSelectedRow();
        try{
            this.selectedPatient = this.patients.get(selectedRowIndex);
            DatabaseConnector.deletePatient(selectedPatient);
            System.out.println("Patient deleted successfully");
            populateTable();
        }catch(Exception e){
            System.out.println("Unable to delete the patient.");
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        enableAll();
        int selectedRowIndex = this.patientjTable.getSelectedRow();
        this.selectedPatient = this.patients.get(selectedRowIndex);
        populateData();
    }//GEN-LAST:event_editButtonActionPerformed

    private void submitEditedRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditedRowButtonActionPerformed
        // TODO add your handling code here:
        Patient newPatient = new Patient();
        newPatient.setFirstName(this.FirstNameJTextField.getText());
        newPatient.setLastName(this.LastNameJTextField.getText());
        newPatient.setAge(this.AgeJTextField.getText());
        newPatient.setPhoneNumber(this.PhoneJTextField.getText());
        newPatient.setEmail(this.EmailJTextField.getText());
        newPatient.setGender(this.buttonGroupGender.getSelection().getActionCommand());
        newPatient.setPatientType(this.patientJComboBox.getSelectedItem().toString());
        
        try{
            DatabaseConnector.updatePatient(selectedPatient, newPatient);
            System.out.println("The record has been updated");
            populateTable();
        }catch(Exception e){
            System.out.println("Error in updating the database");
            System.out.println(e);
        }
    }//GEN-LAST:event_submitEditedRowButtonActionPerformed
   
    public void populateTable(){
        this.patients = DatabaseConnector.getPatients();
        DefaultTableModel model = (DefaultTableModel) this.patientjTable.getModel();
        model.setRowCount(0);
        for (Patient p1: patients){
            Object [] row = new Object[8];
            row[0] = p1.getId();
            row[1] = p1.getFirstName();
            row[2] = p1.getLastName();
            row[3] = p1.getAge();
            row[4] = p1.getPhoneNumber();
            row[5] = p1.getEmail();
            row[6] = p1.getGender();
            row[7] = p1.getPatientType();
            model.addRow(row);
        }
    }
    
    public void populateData(){
        this.FirstNameJTextField.setText(selectedPatient.getFirstName());
        this.LastNameJTextField.setText(selectedPatient.getLastName());
        this.AgeJTextField.setText(selectedPatient.getAge());
        this.PhoneJTextField.setText(selectedPatient.getPhoneNumber());
        this.EmailJTextField.setText(selectedPatient.getEmail());
        String gender = selectedPatient.getGender();
        if(gender.equals("MALE")){
            this.buttonGroupGender.setSelected(this.JRadioButtonMale.getModel(), true);
        }else if(gender.equals("FEMALE")){
            this.buttonGroupGender.setSelected(this.JRadioButtonFemale.getModel(), true);
        }else{
            this.buttonGroupGender.setSelected(this.JRadioButtonOthers.getModel(), true);
        }
        
        this.patientJComboBox.setSelectedItem(selectedPatient.getPatientType());
        //this.imgJLabel.setIcon(p1.getProfilePicture());
    }
    
    public void enableAll(){
        this.FirstNameJLabel.setEnabled(true);
        this.LastNameJTextField.setEnabled(true);
        this.AgeJTextField.setEnabled(true);
        this.PhoneJTextField.setEnabled(true);
        this.PhoneJTextField.setEnabled(true);
        this.EmailJTextField.setEnabled(true);
        this.JRadioButtonMale.setEnabled(true);
        this.JRadioButtonOthers.setEnabled(true);
        this.patientJComboBox.setEnabled(true);
        this.submitEditedRowButton.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JTextField AgeJTextField;
    private javax.swing.JLabel EmailJLabel;
    private javax.swing.JTextField EmailJTextField;
    private javax.swing.JLabel FirstNameJLabel;
    private javax.swing.JTextField FirstNameJTextField;
    private javax.swing.JLabel GenderJLabel;
    private javax.swing.JRadioButton JRadioButtonFemale;
    private javax.swing.JRadioButton JRadioButtonMale;
    private javax.swing.JRadioButton JRadioButtonOthers;
    private javax.swing.JLabel LastNameJLabel;
    private javax.swing.JTextField LastNameJTextField;
    private javax.swing.JLabel PhoneJLabel;
    private javax.swing.JTextField PhoneJTextField;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> patientJComboBox;
    private javax.swing.JLabel patientTypeJLabel;
    private javax.swing.JTable patientjTable;
    private javax.swing.JButton submitEditedRowButton;
    // End of variables declaration//GEN-END:variables
}
